// <auto-generated />
using System;
using HundeRally.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HundeRally.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240430060532_MakingSureDbIsOk2")]
    partial class MakingSureDbIsOk2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HundeRally.WebAPI.Entities.Obstacle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ObstacleCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObstacleCategoryId");

                    b.ToTable("Obstacles");
                });

            modelBuilder.Entity("HundeRally.WebAPI.Entities.ObstacleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObstacleCategories");
                });

            modelBuilder.Entity("HundeRally.WebAPI.Entities.Obstacle", b =>
                {
                    b.HasOne("HundeRally.WebAPI.Entities.ObstacleCategory", "ObstacleCategory")
                        .WithMany()
                        .HasForeignKey("ObstacleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObstacleCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
